version: '3.8'

services:
  app:
    container_name: nestjs-mysql
    image: nestjs-mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}' 
    restart: unless-stopped  
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DB: ${DATABASE_NAME}
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:8.0.24
    # volumes:
    #   - .docker/data/db:/var/lib/mysql
    ports: 
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: unless-stopped