version: '3.8'


services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports: 
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    restart: always
  
  app:
    container_name: nestjs-mysql
    image: nestjs-mysql
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}' 
    restart: unless-stopped  
    environment:
      MYSQL_HOST: host.docker.internal
    depends_on:
      - mysql

